apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: lscr.io/linuxserver/bookstack:latest
        env:
        - name: APP_URL
          value: "__APP_URL__"
        - name: TZ
          value: "Etc/UTC"
        - name: APP_KEY
          value: "base64:wJ6pLp8+nQ4yL8mN1gZqXvR2bS5cE7hF9aK3jD0iG+s="
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_PASS
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_DATABASE
        ports:
        - containerPort: 80
        volumeMounts:
        - name: bookstack-config
          mountPath: /config
      volumes:
      - name: bookstack-config
        persistentVolumeClaim:
          claimName: bookstack-config-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
