apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        env:
        - name: url
          value: "http://adb89c008cfc14dc8bd4e12996aee084-1441024862.us-east-1.elb.amazonaws.com" # This will be the public URL of your blog
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          valueFrom:
            secretKeyRef:
              name: ghost-db-secret
              key: DB_HOST
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: ghost-db-secret
              key: DB_USER
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: ghost-db-secret
              key: DB_PASS
        - name: database__connection__database
          valueFrom:
            secretKeyRef:
              name: ghost-db-secret
              key: DB_DATABASE
        - name: mail__transport
          value: "SMTP"
        - name: mail__options__service
          value: "SES"
        - name: mail__options__port
          value: "465"
        - name: mail__options__host
          valueFrom:
            secretKeyRef:
              name: ghost-mail-secret
              key: SES_HOST
        - name: mail__options__auth__user
          valueFrom:
            secretKeyRef:
              name: ghost-mail-secret
              key: SES_USER
        - name: mail__options__auth__pass
          valueFrom:
            secretKeyRef:
              name: ghost-mail-secret
              key: SES_PASS
        - name: mail__from
          valueFrom:
            secretKeyRef:
              name: ghost-mail-secret
              key: MAIL_FROM_ADDRESS
        ports:
        - containerPort: 2368
          name: http
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content-pvc
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ebs-sc
  resources:
    requests:
      storage: 1Gi
