apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: lscr.io/linuxserver/bookstack:latest
        env:
        - name: APP_URL
          value: "http://localhost" # This will be updated by the service's external IP
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_PASS
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bookstack-db-secret
              key: DB_DATABASE
        ports:
        - containerPort: 80
