apiVersion: v1
kind: Secret
metadata:
  name: bookstack-secrets
type: Opaque
data:
  db_host: REPLACE_WITH_BASE64_DB_HOST
  db_database: REPLACE_WITH_BASE64_DB_DATABASE
  db_user: REPLACE_WITH_BASE64_DB_USER
  db_pass: REPLACE_WITH_BASE64_DB_PASS
