apiVersion: v1
kind: Secret
metadata:
  name: ghost-db-secret
type: Opaque
data:
  # Values are base64 encoded. They will be replaced by the CI/CD pipeline.
  # echo -n "your-value" | base64
  DB_HOST: __DB_HOST__
  DB_USER: __DB_USER__
  DB_PASS: __DB_PASS__
  DB_DATABASE: __DB_DATABASE__
